version: '3.4'

services:
  telegram-notifier:
    image: eatery.notifier
    build:
      context: .
      dockerfile: ChelindbankEatery/Dockerfile
    environment:
      - telegram.bot.channel=""
      - telegram.bot.token=""
    networks:
      - backend
      - frontend
  web:
    image: eatery.web
    build:
      context: .
      dockerfile: ChelindbankEateryWeb/Dockerfile
    volumes:
      - menufolder:/mnt/N/tmp/tmp
    networks:
      - backend
    ports:
      - 7006:7006
    environment:
      - ASPNETCORE_URLS=http://+:7006

networks:
  frontend:
    driver: bridge
  backend:

volumes:
  menufolder:
    external: true